### ISSUE TITLE
Create `~/.config/fontman` directory if it does not exist

### ISSUE THREAD

**Issue by gmisail** [gmisail/fontman-client#8]
This directory is where we will store authentication credentials, `fontman` configuration files, etc... This is different from the `~/.fontman` folder; this is purely for configuration details, not font data. 

That being said, we will check for it in a similar way; on command invocation, load in the configurations & authentication details. If they don't exist, create them.

**Comment by meowox** [comment]
Resolved in c6b9479d149743b38156f0c8883cb0c35627f726.
